### ISSUE TITLE
What is the next step?

### ISSUE THREAD

**Issue by alirezaashrafi** [farsirocks/timeline#1]
We have implemented Farsi and Jalali timeline.
But it's available just on pure HTML.
I think. As the next step. We can implement it in a React-based component.

**Comment by noghte** [comment]
The priority is to fix issues in showing numbers and starting months from فروردین.
Then, to make it work in both calendar systems (شمسی و میلادی). For example, when the user changes a dropdown input, the timeline calendar system changes.
