### ISSUE TITLE
disable zoom-out at the end

### ISSUE THREAD

**Issue by noghte** [farsirocks/timeline#2]
After keeping zoomin out, in the end, the NaN message appears. Please disable zoom-out functionality when it is too much.
![zoom](https://user-images.githubusercontent.com/1125326/118407149-5cc3b980-b64d-11eb-9b38-1314eafc49fd.JPG)

**Comment by alirezaashrafi** [comment]
This issue has been solved by adding "zoomMax" attribute in Timeline options

`zoomMax: 1000 * 60 * 60 * 24 * 31 * 12 * 5,`

maximum 5 years are zoomble
